### ISSUE TITLE
Merging the projects

### ISSUE THREAD

**Issue by peerchemist** [Crypto-toolbox/pandas-technical-indicators#1]
Hi,

do you maybe want to merge the projects?
https://github.com/peerchemist/finta

**Comment by nlsdfnbch** [comment]
Hey @peerchemist!

Feel free to incorporate anything from my code into your project - I created it as a static link from the mentioned post in the project's README, so it's hardly a proper project. 

I'd gladly link to your project, though! It looks alot better than my copy-pasta and half-hearted pepping :)

**Comment by deepbrook** [comment]
Link added to readme (sorry it took so long!).
