### ISSUE TITLE
TypeError: Cannot compare type 'Timestamp' with type 'int'

### ISSUE THREAD

**Issue by axano** [Crypto-toolbox/pandas-technical-indicators#9]
when calling function like this 

     dataframe = lib.indicatorCalculations.relative_strength_index(dataframe['bitcoin'], n=14)

I get the following error 

     TypeError: Cannot compare type 'Timestamp' with type 'int'

my dataframe is like this: 

                 bitcoin                  
                    High      Low    Close
     Date                                 
     2018-05-14  8881.12  8367.97  8716.79
     2018-05-15  8836.19  8456.45  8510.38
     2018-05-16  8508.43  8175.49  8368.83
     2018-05-17  8445.54  8054.12  8094.32
     2018-05-18  8274.12  7974.82  8250.97
     2018-05-19  8372.06  8183.35  8247.18

**Comment by nlsdfnbch** [comment]
Have you tried converting the `date` field to an int representing the date as `ms`?

**Comment by axano** [comment]
The problem was that the dataframe was not formatted right. I had to pass the dataframe through a normalization function

     def normalizeDataFrameFromCoinMarketCap(dataframe):
        desired_width = 320
        pd.set_option('display.width', desired_width)
        np.set_printoptions(linewidth=desired_width)
        pd.set_option("display.max_columns", 10)
        dataframe.columns = dataframe.columns.get_level_values(1)
        dataframe.reset_index(inplace=True)
        return dataframe
